### PR TITLE
remove hungarian notation

### PR DESCRIPTION
**Pull request by nick-a-schneider**
Changes: [WIP]
 - [x] Remove data type prefix from typedefs and struct members
 - [x] Add `jock_` prefix to user facing API functions
 - [x] Clarify function vs. variable format:
    @JGoard  Currently we're using camelCase for functions *and* variables, and PascalCase for typedefs. Do we want to switch either functions or variables to snake_case to better distinguish them? There's a reasonable argument to be made for either, or leaving as-is, just comes down to our preference. Personally I'd  make function snake_case or leave as is

### CODE REVIEW

**Comment by JGoard** [comment]
@nick-a-schneider What if we do this...

- PascalCase for Functions and structs/typedef names
- camelCase for variables
- snake_case (maybe?) for private variables (I saw you were using a var_ to denote private vars, but maybe this could be an easier to the eye solution

**Comment by nick-a-schneider** [comment]
@JGoard I'd really prefer to reserve PascalCase for just structs/typedefs/enums. What if *all* variables were snake_case, and **everything** private was hidden behind a `void* internals` sub-struct?

**Comment by JGoard** [comment]
Sure, lets do that @nick-a-schneider

**Comment by nick-a-schneider** [comment]
@JGoard variable names are updated, and I included a `clang-tidy` config file and a suggested extension to use it. Not sure how to get clang-tidy running from inside a container yet but flushing out that tooling could get kicked down the road a bit

**Comment by JGoard** [comment]
Looks good to merge

**Pull request merged**
